---
title: "01_A_sizeeffect"
author: "Marianela Pini"
date: "2023-08-18"
output: html_document
---

## Loading packages
```{r, echo=FALSE, eval=FALSE}
install.packages("metafor")
install.pachakes("dplyr")
install.packages("ggpubr")
library(metafor)
library(dplyr)
library(ggpubr)
```
## Loading data
```{r eval = TRUE, echo = TRUE}
library("here")
data<- read.csv(here::here("Data/processed", "data_te.csv"), sep = ";")
data<- read.csv("~/Brasil/mestrado/metaanalysis/Data/processed/data_te.csv",
                     sep = ";",
                     stringsAsFactors = FALSE,
                     fileEncoding = "latin1")
```
## Calculate effect size
Calculating effect size between treatment, plants with invasive plant (Leucaena),
and control, plants without invasive plant (Leucaena)

# Loading packages
#From Nakagawa et al. (2021)
```{r eval = TRUE, echo = FALSE}
# need package pacman to install the rest
# required packages
pacman::p_load(R.rsp,
               tidyverse,
               metafor,
               gt,
               pander,
               stringr,
               openxlsx,
               rotl,
               ape,
               knitr,
               kableExtra,
               patchwork,
               here,
               lme4,
               readxl,
               orchaRd,
               patchwork,
               cowplot,
               metaviz,
               meta,
               ggplotify,
               grid,
               dmetar,
               viridis,
               metaAidR,
               ggpubr,
               emmeans,
)
```


            

```{r eval = TRUE, echo = TRUE}
#Transforming numeric
data$MEANc<-as.numeric(data$MEANc)
data$MEANn<-as.numeric(data$MEANn)
data$SDc<-as.numeric(data$SDc)
data$SDn<-as.numeric(data$SDn)
#Getting effect sizes
data <- escalc(measure="SMD", m1i = as.numeric(MEANn), sd1i = as.numeric(SDn), m2i = as.numeric(MEANc), sd2i = as.numeric(SDc),
               n1i = as.numeric(Nn), n2i = as.numeric(Nc), data = data)
```
##Fitting models
Geral model
```{r}
model_geral <- rma.mv(yi, vi, random = ~1 | study_id/outcome_id, data = data)
model_geral
```
##Overall forest plot
```{r, echo= TRUE}
#Overall forest plot
forest(model_geral,
       xlab = "Hedge's g",
       cex = 0.5, 
       order = order(data$study_id), 
       slab = data$reference, 
       header = "Reference",
       ilab=  cbind((data$Nc), (data$Nn)), 
       ilab.xpos = c(-9.5, -8))
abline(h = 0)
X11(width = 14, height = 7)
savePlot(filename = "forestplot.png", type = "png")
```

